// Command gencards regenerates the fixed bingo card tables for BOTH repos from a
// single source, so the Go backend and the TS frontend can never drift.
//
//   - All card IDs 1..TOTAL are freshly generated: deterministic (fixed seed),
//     valid (correct column ranges, unique per column, FREE center) and with a
//     UNIQUE set of 24 numbers — no two cards share the same numbers at all.
//
// It writes:
//   - pkg/bingo/carddata_gen.go        (Go: cardData500 [TOTAL][5][5]int, [row][col])
//   - ../bingo-miniapp/src/lib/cards.ts (TS: flat row-major CARD_TABLE + getCard)
//
// Run from the backend repo root:  go run ./cmd/gencards
package main

import (
	"fmt"
	"math/rand"
	"os"
	"sort"
	"strings"
)

const total = 500

// numSetSig is the canonical signature of a card's 24 numbers (order-independent,
// FREE center excluded). Deduping on this guarantees no two cards share the same
// set of numbers — a strictly stronger uniqueness than distinct layout.
func numSetSig(c [5][5]int) string {
	vals := make([]int, 0, 24)
	for r := 0; r < 5; r++ {
		for col := 0; col < 5; col++ {
			if c[r][col] != 0 {
				vals = append(vals, c[r][col])
			}
		}
	}
	sort.Ints(vals)
	var b strings.Builder
	for _, v := range vals {
		fmt.Fprintf(&b, "%d,", v)
	}
	return b.String()
}

// genCard builds one valid card: each column drawn from its own range, distinct,
// with the center (row 2, col 2 = N) left as the FREE space (0).
func genCard(r *rand.Rand) [5][5]int {
	var card [5][5]int
	for col := 0; col < 5; col++ {
		lo := col*15 + 1
		pool := make([]int, 15)
		for i := range pool {
			pool[i] = lo + i
		}
		r.Shuffle(len(pool), func(i, j int) { pool[i], pool[j] = pool[j], pool[i] })
		idx := 0
		for row := 0; row < 5; row++ {
			if col == 2 && row == 2 {
				card[row][col] = 0 // FREE center
				continue
			}
			card[row][col] = pool[idx]
			idx++
		}
	}
	return card
}

func main() {
	// Generate all TOTAL cards fresh: each valid and with a UNIQUE set of numbers
	// (no two cards share the same 24 numbers). Deterministic via the fixed seed.
	all := make([][5][5]int, 0, total)
	seen := map[string]bool{}
	r := rand.New(rand.NewSource(20240717))
	for len(all) < total {
		c := genCard(r)
		s := numSetSig(c)
		if seen[s] {
			continue
		}
		seen[s] = true
		all = append(all, c)
	}

	if err := os.WriteFile("pkg/bingo/carddata_gen.go", []byte(goFile(all)), 0o644); err != nil {
		panic(err)
	}
	if err := os.WriteFile("../bingo-miniapp/src/lib/cards.ts", []byte(tsFile(all)), 0o644); err != nil {
		panic(err)
	}
	fmt.Printf("wrote %d cards (Go + TS)\n", len(all))
}

func goFile(all [][5][5]int) string {
	var b strings.Builder
	b.WriteString("// Code generated by cmd/gencards. DO NOT EDIT.\n\n")
	b.WriteString("package bingo\n\n")
	b.WriteString(fmt.Sprintf("// cardData500 is the fixed 5x5 layout ([row][col]) for card IDs 1..%d.\n", total))
	b.WriteString(fmt.Sprintf("var cardData500 = [%d][5][5]int{\n", total))
	for i, c := range all {
		b.WriteString("\t{")
		for row := 0; row < 5; row++ {
			b.WriteString("{")
			for col := 0; col < 5; col++ {
				if col > 0 {
					b.WriteString(", ")
				}
				fmt.Fprintf(&b, "%d", c[row][col])
			}
			b.WriteString("}")
			if row < 4 {
				b.WriteString(", ")
			}
		}
		fmt.Fprintf(&b, "}, // %d\n", i+1)
	}
	b.WriteString("}\n")
	return b.String()
}

const tsHeader = `import type { BingoCard } from "@/types/api";

// Code generated by the backend cmd/gencards. DO NOT EDIT BY HAND.
// Byte-for-byte mirror of the server card table (pkg/bingo/carddata_gen.go);
// the server remains the source of truth for win validation.
//
// Each card is a flat 25-int array, row-major (5 rows x B,I,N,G,O columns).
// Index 12 (center) is 0 = FREE.
export const CARD_TABLE: readonly (readonly number[])[] = [
`

const tsFooter = `];

// Reshape cache: repeated lookups (grid preview, game room) reuse the object.
const cache = new Map<number, BingoCard>();

/**
 * getCard returns the fixed bingo card for an id (MIN_CARD_ID..MAX_CARD_ID) as
 * the app's BingoCard shape (numbers[row][col], center = 0 = FREE), or null if
 * the id is out of range. No network — identical to what the server derives.
 */
export function getCard(id: number): BingoCard | null {
  const flat = CARD_TABLE[id - 1];
  if (!flat) return null;
  let card = cache.get(id);
  if (!card) {
    const numbers: number[][] = [];
    for (let r = 0; r < 5; r++) numbers.push(flat.slice(r * 5, r * 5 + 5) as number[]);
    card = { id, numbers };
    cache.set(id, card);
  }
  return card;
}
`

func tsFile(all [][5][5]int) string {
	var b strings.Builder
	b.WriteString(tsHeader)
	for i, c := range all {
		b.WriteString("  [")
		first := true
		for row := 0; row < 5; row++ {
			for col := 0; col < 5; col++ {
				if !first {
					b.WriteString(",")
				}
				first = false
				fmt.Fprintf(&b, "%d", c[row][col])
			}
		}
		fmt.Fprintf(&b, "], // #%d\n", i+1)
	}
	b.WriteString(tsFooter)
	return b.String()
}
